#!/bin/bash -e

if [ "$#" -lt 2 ]; then
    echo "Usage $(basename $0) charm-dir charm-uri"
    exit 1
fi

RENDERED_CHARM_DIR="$1"
CHARM_URI="$2"

GIT_UPSTREAM_REPO="git@github.com:CanonicalLtd/archive-auth-mirror"
GIT_UPSTREAM_REMOTE="upstream"

# push the charm to the store and grab the returned version
OUT=$(mktemp)
charm push $RENDERED_CHARM_DIR $CHARM_URI | tee $OUT
PUSHED_CHARM="$(cat $OUT | sed -n 's/^url: //p')"
PUSHED_CHARM_REV=${PUSHED_CHARM##*-}
rm $OUT

REV_HASH=$(awk '{ print $NF; }' "$RENDERED_CHARM_DIR"/repo-info)

# publish the charm
charm release $PUSHED_CHARM --channel=edge
charm grant $PUSHED_CHARM --acl read --set everyone
