#!/usr/bin/env python3
#
# Manage users for repository access through basic authentication.
#

import sys
from os import path

sys.path.append(path.join(path.dirname(__file__), 'lib'))

from archive_auth_mirror.scripts import manage_user

manage_user.main()
