#!/usr/bin/env python3
#
# Mirror a .deb repository
#

import sys
from os import path

sys.path.append(path.join(path.dirname(__file__), 'lib'))

from archive_auth_mirror.scripts import mirror_archive

mirror_archive.main()
