#!/bin/bash
#
# Mirror a repository
#

BASEDIR="$(realpath $(dirname $0)/..)"
SCRIPTNAME="$(basename $0)"

CONFIG_FILE="$BASEDIR/config"
REPO_DIR="$BASEDIR/static/ubuntu"

# Variables used by reprepro
export REPREPRO_BASE_DIR="$BASEDIR/reprepro"
export REPREPRO_CONFIG_DIR="$REPREPRO_BASE_DIR/conf"
export GNUPGHOME="$REPREPRO_BASE_DIR/.gnupg"


log() {
    logger -t "$SCRIPTNAME" -i "$@"
}

# Load the config file if present.
#
# currently, it must define the $SUITE variable
#
if [ -f "$CONFIG_FILE" ]; then
    . "$CONFIG_FILE"
else
    log "config file not found, mirroring disabled"
    exit
fi

REPREPRO="reprepro --outdir $REPO_DIR"

log "starting mirroring"
$REPREPRO --show-percent update "$SUITE"
$REPREPRO deleteunreferenced
log "mirroring completed"
