#!/bin/bash -e
#
# Helper to sign files for reprepro
#

BASEDIR="$(realpath $(dirname $0)/..)"
CONFIG_FILE="$BASEDIR/config"
PASSPHRASE_FILE="$BASEDIR/sign-passphrase"


# From reprepro(1):
#
# It gets three command line arguments: The filename to sign, an empty argument
# or the filename to create with an inline signature (i.e. InRelease) and an
# empty argument or the filename to create an detached signature
# (i.e. Release.gpg).  The script may generate no Release.gpg file if it choses
# to (then the repository will look like unsigned for older clients), but
# generating empty files is not allowed.  Reprepro waits for the script to
# finish and will abort the exporting of the distribution this signing is part
# of unless the scripts returns normally with exit code 0.
#
UNSIGNED_FILE="$1"
INLINE_SIGN_FILE="$2"
DETACH_SIGN_FILE="$3"


# The config file must define the $SIGN_KEY_ID variable
. "$CONFIG_FILE"

GPG="gpg --no-use-agent --batch --passphrase-file $PASSPHRASE_FILE -u $SIGN_KEY_ID"

if [ "$INLINE_SIGN_FILE" ]; then
    $GPG -o "$INLINE_SIGN_FILE" --clearsign -a "$UNSIGNED_FILE"
fi

if [ "$DETACH_SIGN_FILE" ]; then
    $GPG -o "$DETACH_SIGN_FILE" --detach-sig -a "$UNSIGNED_FILE"
fi
