#!/usr/bin/env python3
#
# Helper to sign files for reprepro
#
# From reprepro(1):
#
# It gets three command line arguments: The filename to sign, an empty argument
# or the filename to create with an inline signature (i.e. InRelease) and an
# empty argument or the filename to create an detached signature
# (i.e. Release.gpg).  The script may generate no Release.gpg file if it choses
# to (then the repository will look like unsigned for older clients), but
# generating empty files is not allowed.  Reprepro waits for the script to
# finish and will abort the exporting of the distribution this signing is part
# of unless the scripts returns normally with exit code 0.
#

import sys
from os import path

sys.path.append(path.join(path.dirname(__file__), 'lib'))

from archive_auth_mirror.scripts import reprepro_sign_helper

reprepro_sign_helper.main()
